% TEST_EFIGURE an interactive test function for efigure
%
%  Demonstrates most of the ways that efigure can be used
%
%  see also efigure
%
%  Note: this test was developed in r2015b.
%
% Author   : Robert Cumming
% Copyright: Matpi Ltd
%            Developers of Matlab GUI Toolbox 
%               - free demo from www.matpi.com or 
%               -               https://github.com/robertjcumming/matpigui
%               -  contact @ matpi.com
%
function test_efigure()
  
  %% Set up for all future figures 
  %      Note: Set up can be called multiple times -> this is self managed.
  efigure ( '*setup*' );

  close all
  % call figure normally
  hFig = figure;
  addUIC(hFig,'Toolbar icons added to figure', 1);
  
  % figure generated by gcf
  hFig = gcf;
  addUIC(hFig,'Toolbar icons added to gcf', 1);
  
  % figure generated by plot
  h = plot ( [1:10], [1:10].^2 );
  addUIC(ancestor(h,'figure'),'Toolbar icons added from plot command', 1);
  
  % call figure normally with extra inputs
  hFig = figure ( 'Name', 'Fig with name' );
  addUIC(hFig,'Figure with extra inputs', 1);
  
  %%  Rearrange
  % call figure wiht extra inputs -> but dont rearrange toolbar icons
  efigure ( '*norearrange*' )
  hFig = figure ( 'Name', 'Fig with name' );
  addUIC(hFig,'Figure with extra inputs - no rearrangement', 2);
  
  % call figure with extra inputs -> turn rearrange toolbar icons
  efigure ( '*rearrange*' )
  hFig = figure ( 'Name', 'Fig with name' );
  addUIC(hFig,'Figure with extra inputs - rearangement reenabled', 1);

  %%  disable toolbars being added
  % call figure wiht extra inputs -> but dont rearrange toolbar icons
  efigure ( '*disable*' )
  hFig = figure ( 'Name', 'Fig with name' );
  addUIC(hFig,'Figure with extra inputs - disabled', 3);
  
  % call figure with extra inputs -> turn rearrange toolbar icons
  efigure ( '*enable*' )
  hFig = figure ( 'Name', 'Fig with name' );
  addUIC(hFig,'Figure with extra inputs - reenabled', 1);
  
  %% add to your own toolbar
  hFig = figure ( 'Toolbar', 'none' );
  hToolbar = uitoolbar ( 'parent', hFig );
  efigure(hToolbar)
  addUIC(hFig,'Added to your own new toolbar', 4);

  % call figure wiht extra inputs -> but dont rearrange toolbar icons
  efigure ( '*resetAll*' )
  hFig = figure ( 'Name', 'Fig with name' );
  uiwait ( msgbox ( 'Press me to add icons to toolbar', 'continue' ) );
  efigure(hFig);
  addUIC(hFig,'toolbars added post figure creation - automated setup diabled', 1);
  
  %%
  disp ( 'efigure has been reset - to enable for all figures, type:' );
  disp ( '   The best place for this is in your startup.m' );
  disp ( 'efigure ( ''*setup*'' ) ' );
end
% A worker function to add a string to the figure to help explain the tests.
function addUIC ( hFig, str, v )
  switch v
    case 1
      str = sprintf ( '%s\nCheck toolbar icons added next to Save button\nThen close me to continue', str );
    case 2
      str = sprintf ( '%s\nCheck toolbar icons added at end\nThen close me to continue', str );
    case 3
      str = sprintf ( '%s\nNo toolbar added\nThen close me to continue', str );
    case 4
      str = sprintf ( '%s\nToolbar icons added\nThen close me to continue', str );
  end
  if verLessThan ( 'matlab', '8.4' )
    uiwait ( msgbox ( str ) );
    delete(hFig);
  else
    uicontrol ( 'style', 'text', 'parent', hFig, 'string', str, 'Units', 'normalized', 'Position', [0.2 0.8 0.6 0.1], 'HorizontalAlignment', 'Left' );
    uiwait(hFig);
  end
end